#!/bin/sh

echo "Running program $1"

echo "Compiling the code"
as --32 -o "$1.o" "$1.s"

echo "Running linker"
ld -m elf_i386 -s -o "$1" "$1.o"

echo "Executing"
./$1
printf 'Result: %d\n' $?

echo "Cleanup"

rm $1
rm "$1.o"

echo "Done!"
